# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae8b55c8be34dab0b5f6a05ca36238fb6075ca88d1e4423b4c8feb87d8d7b97254694881d7f3c8640405867e5704a00424e045f3eda55c2f39f702e712b8ffd5

test:
  secret_key_base: 314133dc4f03e8a0311da5067842ee22c18bc574906c7143b4ec104832a36ef5185cbbb6b3bcbeed99e45881cbaf8a9219d2eab4fbf85d9ed032772c8e461105

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
